### ISSUE TITLE
[Config?] Big Torch from Kibe does not prevent Werewolves and Ghosts from spawning

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#103]
I dunno if there is a config for this, but the Big Torch is not preventing werewolves from spawning, which is an issue.
Also doesn't prevent ghosts, which isn't really an issue, but I thought I should mention it anyway.

**Comment by k3nw4y** [comment]
iirc the warewolfs spawns based on moonphase and not light level

**Comment by IcyJalapeno** [comment]
Werewolf (Villagers), Vampires spawning randomly around you in well light areas, within the Big Torch as well.  

Candelabra current ranges are way to small imo. Way too many damn ghosts. My mini-map is honestly full of ghosts simply because Big Torch blocks everything else besides anything Bewitchment. 

Either limit the max number of ghosts, or make the Candelabra's effect chunk area bigger and make them follow in line with the Big Torch.

**Comment by yorii** [comment]
Yeah, the biggest issue is the combination of the two, using a big torch to disable all other spawns, makes it so that the server is more eager to spawn an extra amount of bewitchment mobs. On our server we have several big torches around the spawn area, which makes it so that during full moons, an actual horde of werewolves sometimes spawn in, which can easily become impossible for a new player to even deal with.

But at least candelabras luckily work reasonably well to prevent ghosts from completely taking over.

**Comment by yorii** [comment]
Fixed in the latest release of Bewitchment :) thanks MoriyaShiine!
