### ISSUE TITLE
world/character corrupted 

### ISSUE THREAD

**Issue by Virgil404** [TeamAOF/All-of-Fabric-5#118]
i think my save corrupted somehow because the game character cant interact with the world it can break and place blocks but cant use any items cant kill any mobs and cant take any damage cant even kill the character with commands. If i try to change the gamemode or use any command to try to fix it doesnt work. if i exit the game it stuck at the saving world screen so i had to close it from the task manager. the issue is happend around when i milked a cow and tried to drink the milk to remove a potion effect

**Comment by psuedolatry** [comment]
I am having the same issue. Not caused by the same problem though... a bunch of different things are causing this issue for me which leads me to believe that the modpack in itself isn't stable right now. I have had it happen across multiple different worlds, as I thought the same as you, world corruption. But no, it doesn't seem to be that. It seems to be something with the modpack itself.

**Comment by yorii** [comment]
can't replicate

**Comment by Virgil404** [comment]
i figured what caouses the problem at least for me.  if i go back to that area where noticed the problem after i reloaded the map this bug always comes back. but  after i reloaded the map and avoided that area it had no problem. whenever i go back to that specific part of the map this bug always happens.  so it maybe have to do something with the world generation or structure generation

**Comment by psuedolatry** [comment]
Oh thats a good idea. Let me try that as well.

**Comment by k3nw4y** [comment]
can you post the crash log when it crashes @Virgil404 ?

**Comment by psuedolatry** [comment]
@k3nw4y well thats the thing... The game doesn't technically "crash." It's more akin to a massive lag spike that literally never goes away. One time I tried to just wait and see if it passes, 30 min later everything is still frozen. I can't shift off the reindeer I was on, can't open chest, can't take damage, all mobs frozen, ect. Even when I close the game and it freezes on the saving screen and then me finally going and shutting down via task manager, it still doesn't populate a crash report, because it didn't crash.

**Comment by Virgil404** [comment]
it didnt crash but i took a look on the logs and around the time whentthat bug happens and i shut it down from the task manager it throws the same java.lang.reflect.InvocationTargetException like 100 times .so maybe that causes the problem. here is the log file [ https://easyupload.io/2367e1](url)
