### ISSUE TITLE
[Recommendation] Bewitchment

### ISSUE THREAD

**Issue by MoriyaShiine** [TeamAOF/All-of-Fabric-5#14]
Issues that caused it to be removed last time are gone / solvable now

-lag is no more
-curses can be disabled
-individual poppets (voodoo, vampiric, etc) can now be disabled

**Comment by Monster-Zer0** [comment]
I am a big fan of you and your work. TBH the biggest reason my personal vote was to remove is because it had the feel that it was such a big mod that it almost felt like it needed a modpack centered around it and anything else was just an insult to it.

HOWEVER

Aof5 kinda looking malnourished.. seeing as not all the mods have updated yet. Adding Bewitchment might give it some meat on it's bones.

I Vote yes.. because also I want to use bewitchment in Skylore.. but Aof5 can be the test dummy @ImAK9

**Comment by ImAK9** [comment]
Added in 0.2.4
