### ISSUE TITLE
Dark enchanter bugged, cost absurd amount of xp

### ISSUE THREAD

**Issue by martinsetupx** [TeamAOF/All-of-Fabric-5#177]
Dark enchanter cost a lot of xp after the newest update, making it almost useless
![unknown](https://user-images.githubusercontent.com/101174650/157198880-611b5317-4a21-47b7-8df6-e1154477be06.png)

**Comment by yorii** [comment]
Already solved for next release, and already fixed in current live servers.
You can edit the config yourself for your local server/singleplayer world, or simply deleting the file will revert it back to the mods original default values.

minecraft\config\dark-enchanting.json5

Or you can grab the updated config file from the dev branch: https://github.com/TeamAOF/All-of-Fabric-5/blob/dev/config/dark-enchanting.json5
