### ISSUE TITLE
[Bug] Upgrading enchated books with Spectrum 

### ISSUE THREAD

**Issue by SubarcticPaper** [TeamAOF/All-of-Fabric-5#197]
There seems to be a bug where you cannot upgrade enchanted books on the Spectrum enchanting.

**Comment by yorii** [comment]
Probably already fixed for next update with AdventureZ 1.4.10, earlier versions caused some inconsistencies with enchantments.

**Comment by DaFuqs** [comment]
https://github.com/KubeJS-Mods/KubeJS/issues/293

KubeJS breaks those because it completely replaces the vanilla recipe manager.
On more technical terms: It unconditionally cancels a vanilla function and replaces it with their own with no way for other mods to still trigger their code. But they will look into it. :)

**Comment by yorii** [comment]
ohoo, why do so many things need to tinker with enchanting functions even :D

**Comment by DaFuqs** [comment]
In that case its not even enchanting for once. More like Spectrums inability to inject Recipes into the Recipe Manager in-code (without the use of json), because it has been completely replaced.

[Spectrum uses a single recipe.json to define a list of final recipes](https://github.com/DaFuqs/Spectrum/wiki/Custom-Enchantment-Upgrade-Recipes#Example), to make the files more maintainable, so upgrading an enchant from level 1=>2, 2=>3, ... can be defined in a single json, and not hundreds of json files for each upgrade step. Could have happeded to any recipe type that uses such a mechanism, not only enchanting. Enchanting is not even touched at all at that point, it's more the recipe loading that is messed up.
