### ISSUE TITLE
Enchantment loop for theoretical max enchants

### ISSUE THREAD

**Issue by Justicetom21** [TeamAOF/All-of-Fabric-5#204]
Using the Biome Makeover Altar, using the Infusion Table to take the (upgraded) enchantment off the item, and then using the Mana Enchanter from Botania to enchant a new item with the book you just created, you can loop any enchantment to theoretically infinite values (though the mana cost involved increases significantly)

honestly i don't think this should be fixed but ig it kinda op

**Comment by InFuRiTy** [comment]
I would have suggested to penalize the leveling up even more to like 200%,300% or even a 1000% of mana needed per level up.
But this kind of nerf can be easily  be bypassed by everyone if they just make several ridiculous mana gen setups to compensate for the scaled up mana costs or they could just wait/afk to get the amount they need.

i do agree that is a neat mechanic to have but can you imagine having sm spend like a month grinding MI to be able to get the Quantum sword only to find out they were surpassed by sm else who grinded  botania for a few days and got a wooden/stone/iron/diamond sword  with sharpness 50 or 100?
not to mention the server latency issues that may arise if sm has a pick with like fortune 50 and mines a single block of diamond and it explodes in literally stacks  of items.
now im not saying getting a 100 Sharp. sword or a fort. 50 pick is an easy task by a long shot..
im just mentioning some extreme worst case scenarios but they are there..
and since the servers we're playing ARE online community servers and are advertised the kind of people who would do sm like that will eventually end up in one of them trying to do it just for fun and giggles or maybe for sm some serious who knows..

Again really cool mechanic to have but i would love to see it staying in the pack!!
Maybe the devs can implement a hard limit of some kind or limit what enchantments can be scaled up!!
