### ISSUE TITLE
AOF5 version 1.0.1 crashing on startup

### ISSUE THREAD

**Issue by zZuud** [TeamAOF/All-of-Fabric-5#224]
Hi there,
Me and my mates have a 1.0.1 aof5 server going at the moment and all of our clients have started crashing all at the same time.
we are all getting the same error and I'm not sure why as it was working 15 hours ago or so. 1.0.0 and some of the other versions are having the same issue. We can't change the server over because McProhosting doesn't have the other versions available.
Attached is the latest log
[latest.log](https://github.com/TeamAOF/All-of-Fabric-5/files/8394449/latest.log)
Thanks

**Comment by suprra** [comment]
I have the same error, it is something to do with some friggin april fools. Tis cool if they wanna do something pranky, but breaking the game on a friday is not on my list of cool >.>
I don't know how to fix it, think I'm gonna hit up reddit.

See this line in your log
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection check

**Comment by F1r3w477** [comment]
Updating to 1.1.3 will fix the issue. Otherwise if you want to stay on older version you can replace the current Indistrial Revolution with this one: [Industrial Revolution 1.13.8-BETA](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3725959)

**Comment by zZuud** [comment]
> Updating to 1.1.3 should fix the issue. Otherwise, if you want to stay on older version, you can replace the current Industrial Revolution with this one: [Industrial Revolution 1.13.8-BETA](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3725959), and that should work.

Yeah this worked cheers
