### ISSUE TITLE
AE2Things Advanced Inscriber Bug - Slots don't lock when piping items in

### ISSUE THREAD

**Issue by altech6983** [TeamAOF/All-of-Fabric-5#259]
If you attach a hopper to any side or use MI pipes and pipe more than one stack into the inscriber it will fill up other slots with the same item.

This bug has been fixed in the latest version of AE2Things (https://github.com/ProjectET/AE2Things/issues/8) but is for 1.18.2 and so I can't just replace it and fix the problem.

AoF5 - 1.1.5

**Comment by dandin87** [comment]
I'm not really sure the point of this issue is? To bug us for the 1.18.2 update? To try and get us to have the fix back ported? The 1.18.2 update is already here on github, and if you know how you can make the pack from these files. Otherwise it was released early for Patreons. The pack update was already posted to Curseforge Friday, but is still waiting for review.

**Comment by altech6983** [comment]
No sorry, I didn't realize y'all already had a 1.18.2 release on here. It was just an annoying bug I found and figured I would report it because I couldn't fix it just by dropping in the updated mod. 

Thank you for the work you do on the pack. Have a good one.
