### ISSUE TITLE
Datapack error, when updating 1.18.1 worlds to pack v1.2.0+

### ISSUE THREAD

**Issue by Juisader** [TeamAOF/All-of-Fabric-5#278]
When trying to load a previous world after updating to the latest version, this error message was received and safe mode does nothing. When checking the datapacks folder there is nothing there. 
![image](https://user-images.githubusercontent.com/99689638/168495667-92466067-3f64-4895-a618-0356639f2088.png)

**Comment by Trebolt23** [comment]
Can also attest to having this issue, updating from AOF5 version 1.1.4 to 1.2.2.

**Comment by dandin87** [comment]
To update a single player world from 1.18.1 (pack version 1.1.5 or sooner) to 1.18.2 (1.2.0+) follow the directions below.
NOTE If you added mods to the pack. you will need to run the server first before copying the old world over. Once the server ran once. Close it, add your updated mods to the server mods folder, now follow the directions below and delete the world folder that is already on the server.

Rename your save folder world
download and extract the server pack files. You will also need java 17 installed. the one Minecraft client uses is not installed and so your OS is not aware of it.
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5/download/3784049
java 17 https://adoptium.net/download
Copy the renamed world folder to the folder you extracted the server files from. 
run startserver.bat if windows or startserver.sh if linux
type true when its asks you to accept the EULA.
Once it finishes loading, close the window then copy the world folder back to your single player saves folder and rename if you want.
Now it will load in single player. 
This is because of a BYG issue. They are not going to fix it as they did make a warning about breaking worlds. Luckily it can be worked around. The server throws the same error as client but continues to load. Whereas the client will kick you back to the title screen.

**Comment by Whitecker** [comment]
can you please a little bit more describe steps to change into new version single world ? I was trying it but not successful. installed java JDK 17, sever pack download, extract, put there save and than run the startserver.bat. accepted eula and the download was finished. Copied the world folder back to my single player saves folder. Still not same fault. 
thanks in advance

**Comment by dandin87** [comment]
You will now need to copy the mods folder from the client to the server folder as curseforge API changes broke server starter from downloading the mods
