### ISSUE TITLE
[Recipe] Let Indrev and Tech Reborn compressors make Battery Alloy plates & curved plates and Tungsten nuggets

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamAOF/All-of-Fabric-5#334]
Indrev and Tech Reborn compressors cannot process Battery Alloy into plates or curved plates, nor can they process tungsten tiny dusts into nuggets. This is inconvenient, as it means I have to switch to a slower MI compressor just to handle battery alloy or tungsten. It especially makes little sense that TR and Indrev machines can handle tungsten in other forms, just not the tiny dust to nugget recipe. I would like to see the relevant recipes added to Indrev and Tech Reborn's compressors.

Related to #294

**Comment by yorii** [comment]
The selection of recipes that are used exclusively by and for MI are tailored so that they cannot be processed through other machinery. Battery Alloy plates and Tungsten Tiny Dusts are respectively only used by, and only created by MI, therefore it was decided that only MI can process those recipes.

Materials that are used for or created by other mods as well as MI will receive compatibility recipes. The rings I will try to write a PR for, but this specific issue will not be approved as it was already recently denied in my last contribution on the matter of plate recipes: https://github.com/TeamAOF/All-of-Fabric-5/issues/179
