### ISSUE TITLE
Tech Reborn Grinder is impossible to craft.

### ISSUE THREAD

**Issue by matiejus** [TeamAOF/All-of-Fabric-5#349]
The recipe is present, although not sure if it is correct. If I recall correctly the grinder did not need oxidized cut copper in the recipe, but that could have changed. As it stands, following the provided recipe does not allow to craft it.

**Comment by Immow** [comment]
I have the exact same issue. I tried crafting the oxidized block in different way's to no avail.

**Comment by catt0** [comment]
I checked the recipe in kubejs/server_scripts/recipetypes/techreborn/shaped.js You need to craft the grinder with an Industrial Revolution fan instead of the copper block in the top middle slot. (Search for @indrev fan in REI for the exact item). Only a workaround, not sure what causes this recipe error.
