### ISSUE TITLE
[Suggestion] Painter's Blocks

### ISSUE THREAD

**Issue by Juuxel** [TeamAOF/All-of-Fabric-5#35]
*I don't want a lot for Christmas / There is just one thing I need...*

...which is [Painter's Blocks](https://curseforge.com/minecraft/mc-mods/painters-blocks) in AOF5 :wink: (yes it's my mod)

**Comment by Shnupbups** [comment]
wow what kind of self-obsessed person would suggest their own mod be added
btw make sure to check out #34 and support me on ko-fi https://ko-fi.com/shnupbups

**Comment by dandin87** [comment]
> _I don't want a lot for Christmas / There is just one thing I need..._
> 
> ...which is [Painter's Blocks](https://curseforge.com/minecraft/mc-mods/painters-blocks) in AOF5 😉 (yes it's my mod)

Getting this error with Painter's Blocks... I assume maybe its related to FREX? Either way that would need to be resolved as without Indium, Sodium won't work with the pack correctly.

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!
Caused by: java.lang.UnsupportedOperationException: A second rendering plug-in attempted to register. Multiple rendering plug-ins are not supported.
https://paste.alloffabric.com/gecetuzofo.yaml

**Comment by Makonede** [comment]
Got almost the exact same crash as @dandin87, just that I'm not using Painter's Blocks.

**Comment by dandin87** [comment]
Other mods can cause this too. not sure what your comment is even for.... In my (TeamAOF Dev) case it specifically happens with Painters Blocks added to the pack, preventing the game from loading. Your comment added nothing to this discussion...

**Comment by Makonede** [comment]
The issue ended up being the JMX mod I had installed. Deleting it fixed the crash.

**Comment by Juuxel** [comment]
That makes sense since Painter's Blocks includes JMX (which in turn includes FREX, which in turn is incompatible with Indium on 1.18 apparently)
