### ISSUE TITLE
Botania: Particle effects missing

### ISSUE THREAD

**Issue by Feuraver** [TeamAOF/All-of-Fabric-5#36]
Pack Ver 0.2.5

The particle effect indicating that the various flowers are operating are missing.

**Comment by Monster-Zer0** [comment]
I think this is fixed in latest version of botania.. at least the last commit to the 1.18 version kinda alludes to this.

however MOST mod issue are gonna be down to the mod dev to fix.. as we just make the modpack.

https://github.com/VazkiiMods/Botania/issues

is where you are gonna want to report this.
