### ISSUE TITLE
Danks Delete most items in a stack when using the Sort keybind

### ISSUE THREAD

**Issue by OverTasked** [TeamAOF/All-of-Fabric-5#381]
Hey I've been having an issue with my Danks. When there is a full stack of one item and other stacks of the same item it will set all the duplicate stacks to 64 items, for example in my gravel crusher I had a dank t3 storing all of my gravel and when I hit the sort key it set all of the values of gravel in each slot to 64 except for one.

**Comment by OverTasked** [comment]
And yes I'm hitting the middle mouse. I know it isn't a function of the Dank mod but it shouldn't result in the deletion of thousands of items.

**Comment by ttamnedlog** [comment]
Oh I agree with that, but I'm not sure it's anything the modpack maintainers can control, other than putting that warning in the quest book (I think it was in the quest book?) or using some different mods.

Speaking of that, one suggestion I might offer to you and the AoF5 maintainers is to remove the Inventory Sorting mod and the SlotLock mod, and replace them with the single mod Inventory Profiles Next. I feel like the main reason to lock your slots is to prevent sorting certain items you always want to keep in the same spots, but Inventory Sorting seems to overpower SlotLock anyway so it's kinda pointless. Inventory Profiles Next has slot locking and sorting built in, and since both are coming from the same mod, it doesn't have any issues working with itself. It also has a lot of of other convenient features. Most importantly, it is highly configurable so some of the features can (and should) be disabled to avoid conflicts in some inventory screens. As a bonus, it does not sort Danks so no worry of accidentally sorting out of muscle memory and destroying your Dank contents.

I'm not sure off the top of my head which of the 3 mods just mentioned (Inventory Sorting, SlotLock, and Inventory Profiles Next) are client side or server side or what, so my suggestion to replace some mods may not be an option if you aren't running your server.

**Comment by OverTasked** [comment]
I'm pretty sure any inventory sorting requires it to be on both client and server so it can receive the packages sent by the client. 

Yeah thanks, I do run my own server so I can look into alternative mods. 

I just wanted to let the devs know just in case it was an unknown bug.

Thanks for the help!

**Comment by OverTasked** [comment]
You might be able to disable the mod when opening a dank's inventory. 
Idk, thanks again though.

**Comment by ttamnedlog** [comment]
> I'm pretty sure any inventory sorting requires it to be on both client and server so it can receive the packages sent by the client.

You'd be surprised! I mean, I too was surprised! Ha. According to Inventory Profiles Next, it is pure client-side. Seems like a recipe for disaster on a server, but I've used it on my vanilla Fabric server for months without issue and have been using it on my AoF5 server for a couple weeks now without issue. Even sorting giant double diamond chests. No idea how it does it and how the server doesn't throw a fit.

**Comment by OverTasked** [comment]
Thanks again,

Yeah it is possible but it could cause some nasty server-> client desync. Also on servers with Anti-cheats it probably would cause some issues.
On vanilla I can't see it being to big a problem but especially with modded content. 

Thanks though, appreciate it.
