### ISSUE TITLE
Lack of content

### ISSUE THREAD

**Issue by Kulturnilpferd** [TeamAOF/All-of-Fabric-5#406]
I came from all of fabric 3 and this new modpack makes me really sad. It lacks huge of content, like the dimension generator, better end, some more dimensions like eden ring. Even mods for better server management are completely missing in this one. Even some blueprints are not working properly like the grinder from tech reborn . I don't know how you guys deside which mods you combine but this is really not going to be ALL of fabric -.-*

**Comment by unilock** [comment]
> the dimension generator

If you're referring to [RFTools Dimensions](https://www.curseforge.com/minecraft/mc-mods/rftools-dimensions), the mod hasn't been ported to Fabric, and therefore cannot be included in this modpack.

> better end

[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend) *was* included in this modpack a one time, but it was removed in v1.0.0. If I recall, biome generation was broken, so that may have been why. (IIRC the biomes wouldn't appear in The End at all.)

> eden ring

As of January 20th, 2022, the devs don't want to add [Eden Ring](https://www.curseforge.com/minecraft/mc-mods/eden-ring) due to it being underdeveloped. https://github.com/TeamAOF/All-of-Fabric-5/issues/114#issuecomment-1017434190

> mods for better server management are completely missing

It's likely such mods aren't included due to them only being useful on servers (of course). You can always add those mods to your server manually.

> some blueprints are not working properly like the grinder from tech reborn .

Known issue. Use a fan instead of a copper block when crafting.
https://github.com/TeamAOF/All-of-Fabric-5/issues/349 https://github.com/TeamAOF/All-of-Fabric-5/issues/400

If you'd like, you can always make mod requests in the form of issues on this bug tracker. Whether the mods you suggest get added is up to the developers of the modpack, of course. Just make sure to label your issue with e.g. "[Mod Suggestion]".

**Comment by Kulturnilpferd** [comment]
Awesome, thanks <3

**Comment by Monster-Zer0** [comment]
Thanks @unilock 

we aren't lazy about it.. we don't include certain mods in next versions because we have tested them out and if the performance is garbage.. then well it goes bye bye.

in terms of content.. AOF isn't at all meant to be a content modpack. it's a kitchen sink modpack.. intended for you to make your own content.. very much in the way the original minecraft is.

it's a way of getting your toes wet in the modded minecraft world.

if you are looking for real hard content. stay tuned as we have an additional modpack coming in the next few months that will blow your socks off.
