### ISSUE TITLE
World stopping [0.2.7]

### ISSUE THREAD

**Issue by DV8ZXPru** [TeamAOF/All-of-Fabric-5#56]
At some point, everything in the game stops. The blocks are destroyed, but nothing falls from them, the generator of the world also stops. Day and night change works, but the rest of life freezes. When you exit the game, you get stuck on saving the world

![world_stop](https://user-images.githubusercontent.com/2900356/147957373-5943dbdf-2f87-47cb-9b1d-1d783384b251.png)

P.S. Playing in singleplayer, not server

**Comment by Chuunkyz** [comment]
this can be caused by a lot of different things, without the logs nobody can help you

**Comment by DV8ZXPru** [comment]
Experiments have shown that this freeze is repeated in the world with a seed: -2888001248626038629, even in version 0.2.5, I have not tried it below. Walk to the northwest of the spawn until plains appear
![world_stop_2](https://user-images.githubusercontent.com/2900356/147979231-f88149d5-b354-4a46-99c2-694c77ffd962.png)

**Comment by Chuunkyz** [comment]
check the logs to see what mod causes the crash...

**Comment by DV8ZXPru** [comment]
no crash logs, since the world is running, there are only the latest logs:
[latest.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/7804219/latest.txt)

**Comment by DV8ZXPru** [comment]
I tried it on the new version 0.2.9, but everything also freezes.
I got angry and decided to turn off the optimization mods (indium, lithium, phosphor, sodium) And thank the gods everything worked.
The chunk where everything froze should have loaded an event with a meteorite from the AE2 mod. Maybe there is a conflict with this mod? Not sure, only guessed

![ae2_meteor_map](https://user-images.githubusercontent.com/2900356/148554088-38a11bf9-d9be-4871-8cd1-12af02dc9430.png)

**Comment by Chuunkyz** [comment]
_what does the logs say_

**Comment by DV8ZXPru** [comment]
[latest_2.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/7829445/latest_2.txt)

**Comment by DV8ZXPru** [comment]
Yes. The problem with the AE2 mod (appliedenergistics2-10.0.0-beta.3). Optimization mods, as it turned out, do not affect this glitch even if they are disabled. Installed in a clean modpack, where there is only one AE2 mod and the same freeze

**Comment by Monster-Zer0** [comment]
@Chuunkyz thanks for the persistence.

@DV8ZXPru I think what Chuunkyz also means to say, is that we can not replicate this issue. I have tried.. even with the seed mentioned.

https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric
add this to get more info about terrain gen. it can break things.. so use at your own risk.

basically, do your thing from a completely new instance... add cyanide.. create the new world with the seed.. get to the point it dies... wait a few... then kill it.

post latest.

this way.. latest encounters in the game are at bottom of log.

if you see some past issues as of recent. this was also an issue with indrev.. if that is an issue with a mod like that.. it's possible other mod devs have to optimize or change things as well. 1.18.1 changed a ton in terrain gen and even with a basic modpack I get extremely slow loading of terrain.

https://github.com/RelativityMC/C2ME-fabric/releases

helped me a lot in loading of chunks. but we can't include it with the pack because.. it's still Alpha and the mod dev suggested to not put it in the pack.. and also because it's not on curseforge.

but you can try it to help with any loading issues.. and report back.

**Comment by DV8ZXPru** [comment]
When the cyanide mod was turned on, there was nothing in the logs at the time of stopping (so I see no reason to post the logs, they are similar to the previous ones)
It is strange that the error does not repeat itself, on this occasion I made a video:

https://youtu.be/pOXHL0_7qiA

But when the C2ME mod was turned on, this chunks in that place were loaded normally and the world was not frozen

**Comment by KaneHart** [comment]
There was an AE2 Stalling out bug that I reported and had fixed. That being said if you think or know it's 100% AE2. Find the same seed go to the same location if it happens create a new 1.18 client with fabric and just AE2 and same seed / location. If it happens let them know of said Seed / Location with whatever version of AE2 you have and kind make sure you test the latest and let them know.  

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5939

**Comment by DV8ZXPru** [comment]
> Find the same seed
If I understood correctly, then there must be a meteorite with lava from below that fell into the water (in my seed it is exactly like this), but such a situation when generating a world is very rare. Okay, I'm closing this issue, apparently this problem is only on my side.
