### ISSUE TITLE
AE2wtlib Wireless Universal Terminal Crash

### ISSUE THREAD

**Issue by EricSihaoLin** [TeamAOF/All-of-Fabric-5#65]
https://pastebin.com/FKxVH7iB

In this crash, we found that there's some problems when charging the AE2WTLIB Wireless Universal terminal in the IndRev Flux Container.

The server has been in a crash loop since, and I think the only way to recover is to delete the tile entity, if I'm not mistaken.

![image](https://user-images.githubusercontent.com/1594432/148584333-4085514f-4294-45d6-9bff-b5a3fa3dc03a.png)

Is this a known compatibility issue?

**Comment by Mari023** [comment]
I think this happens because the terminal has more power stored than it claims it is supposed to have
I am not quite sure why this leads to a crash tho

the best immediate solution is probably setting internalCurrentPower to 0

**Comment by EricSihaoLin** [comment]
> 

Perfect, that worked. Yeah not sure why it leads to a crash because that number is most definitely positive.
Regardless, consider this issue resolved for now.

**Comment by dandin87** [comment]
Going to keep this open, as it is still an issue, and was actually being looked into already because it happened on our server as well.

**Comment by EricSihaoLin** [comment]
I'm not sure if this will help, I think I may have narrowed down why this was an issue in the first place.

There was a AE2WTLib change that modified the way it handled the Infinity upgrade.
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals/files/3595632

Multiple players noticed that after the update from 0.27 to 0.29, their infinity upgrade disappeared from the Wireless Terminal, but the upgrade (4x AE storage) still applied. I'm assuming this was a slot/UI change.

When players went to craft another infinity upgrade and slot it in, it applied the upgrade twice. The game realized that the terminal should not have more than 4.8M AE stored, yet it is drawing more power because technically the limit is 4.8M x 4 (since the booster was doubly applied).

**Comment by Mari023** [comment]
> There was a AE2WTLib change that modified the way it handled the Infinity upgrade. https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals/files/3595632

on curse the changelog is a bit confusing because for some reason it removes newlines

> Multiple players noticed that after the update from 0.27 to 0.29, their infinity upgrade disappeared from the Wireless Terminal, but the upgrade (4x AE storage) still applied. I'm assuming this was a slot/UI change.

the infinity booster card did in fact disappear (it is now a regular upgrade card)
the max power isn't linked to the booster card, but the amount of terminals installed (previously it was always the same, but changeable via a config file, and 3 times as big as it is now with one terminal)

> When players went to craft another infinity upgrade and slot it in, it applied the upgrade twice. The game realized that the terminal should not have more than 4.8M AE stored, yet it is drawing more power because technically the limit is 4.8M x 4 (since the booster was doubly applied).

when adding any upgrade, it recalculates the maximum power, since the upgrade could be an energy card which would increase (or decrease when removing an upgrade), while also voiding any excess power

> Since it is going over the theoretical limit, it may be the root cause of the tile entity crash loop.

the terminal having more power than it's maximum limit is indeed the cause of the crash

the underlying issue is ae2 not correctly handling this (see the pull request I linked)
